spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties: 
      hibernate: 
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
  main:
    allow-bean-definition-overriding: true         
  datasource:
    url: "jdbc:mysql://localhost:3306/itemsharingdatabase?allowPublicKeyRetrieval=true&useSSL=false"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "admin"
    password:  "admin"
    tomcat:
      max-active: 100
      max-idle: 8
      min-idle: 8
security:
  basic:
    enabled: false
server:
  port: 8081     


  
